"""update

Revision ID: 0199653ef396
Revises: 58436f9805e3
Create Date: 2024-02-15 17:03:53.285339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0199653ef396'
down_revision = '58436f9805e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('watermark',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('watermark',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
