"""remove null false

Revision ID: 084bb14102cb
Revises: ce236a03090e
Create Date: 2024-01-02 14:35:35.680703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084bb14102cb'
down_revision = 'ce236a03090e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
