"""country and organization

Revision ID: 0eb501577f92
Revises: a314beff0272
Create Date: 2024-01-05 19:14:47.603685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb501577f92'
down_revision = 'a314beff0272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('organization')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
