"""add include_logo column

Revision ID: 33052f76bb50
Revises: 3f4b152d2ec1
Create Date: 2023-11-16 16:31:12.151418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33052f76bb50'
down_revision = '3f4b152d2ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_logo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('include_logo')

    # ### end Alembic commands ###
