"""update

Revision ID: 39232265330c
Revises: 0eb501577f92
Create Date: 2024-01-12 18:10:19.071741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39232265330c'
down_revision = '0eb501577f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_urls', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('frame_urls')

    # ### end Alembic commands ###
