"""add selectedFrame column

Revision ID: 3f4b152d2ec1
Revises: c65e3a6a08c1
Create Date: 2023-11-15 18:26:17.326312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4b152d2ec1'
down_revision = 'c65e3a6a08c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectedFrame', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('selectedFrame')

    # ### end Alembic commands ###
