"""alter new table

Revision ID: 47e6a27cdee2
Revises: 709a8aa5f3e8
Create Date: 2023-12-19 18:42:14.162664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e6a27cdee2'
down_revision = '709a8aa5f3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base64_string', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('base64_string')

    # ### end Alembic commands ###
