"""add watermark property

Revision ID: 58436f9805e3
Revises: f3a571686d0d
Create Date: 2024-02-13 20:43:19.178859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58436f9805e3'
down_revision = 'f3a571686d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watermark', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('watermark')

    # ### end Alembic commands ###
