"""add tag management

Revision ID: 709a8aa5f3e8
Revises: 97233b76c746
Create Date: 2023-12-19 15:39:11.006980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709a8aa5f3e8'
down_revision = '97233b76c746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_value', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_association',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_gif_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_gif_id'], ['user_gif.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'user_gif_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_association')
    op.drop_table('tag')
    # ### end Alembic commands ###
