"""empty message

Revision ID: 7b341ddc97d4
Revises: 
Create Date: 2023-10-01 20:12:28.148408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b341ddc97d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_constraint('user_gif_resourceid_key', type_='unique')
        batch_op.create_unique_constraint(None, ['resourceId'])
        batch_op.drop_column('resourceid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resourceid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_gif_resourceid_key', ['resourceid'])

    # ### end Alembic commands ###
