"""add default value and change column name

Revision ID: 82c0017326bb
Revises: b681d0b61746
Create Date: 2023-11-07 15:05:15.977967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c0017326bb'
down_revision = 'b681d0b61746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_selected_resolution', sa.String(length=120), nullable=True))
        batch_op.drop_column('selected_resolution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_resolution', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('user_selected_resolution')

    # ### end Alembic commands ###
