"""Add selectedColor to UserGif

Revision ID: 869754423d13
Revises: 7b341ddc97d4
Create Date: 2023-10-12 16:19:55.228030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869754423d13'
down_revision = '7b341ddc97d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectedColor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('selectedColor')

    # ### end Alembic commands ###
