"""add source

Revision ID: 97233b76c746
Revises: ed3c1f06f63f
Create Date: 2023-12-16 15:36:40.140100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97233b76c746'
down_revision = 'ed3c1f06f63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
