"""include ai

Revision ID: 9c1cf48792ab
Revises: 95e38ae68c76
Create Date: 2023-12-10 17:31:14.117151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1cf48792ab'
down_revision = '95e38ae68c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_ai', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('include_ai')

    # ### end Alembic commands ###
