"""add resourceType

Revision ID: 9d92729e667a
Revises: 33052f76bb50
Create Date: 2023-11-27 20:10:55.498662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d92729e667a'
down_revision = '33052f76bb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resourcetype', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('resourcetype')

    # ### end Alembic commands ###
