"""include verify account token

Revision ID: ed3c1f06f63f
Revises: 8c80479f9bf3
Create Date: 2023-12-10 22:46:21.265838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3c1f06f63f'
down_revision = '8c80479f9bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_account_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verify_account_code')

    # ### end Alembic commands ###
