"""click_count

Revision ID: f3a571686d0d
Revises: d00b5d48810e
Create Date: 2024-01-24 20:27:19.529252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a571686d0d'
down_revision = 'd00b5d48810e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_gif', schema=None) as batch_op:
        batch_op.drop_column('click_count')

    # ### end Alembic commands ###
